[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git" 
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/v1.16.1.tar.gz"
    exact = true
    stripComponents = 1
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/fzf-zsh-plugin"]
    type = "git-repo"
    url = "https://github.com/unixorn/fzf-zsh-plugin.git"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-fzf-history-search"]
    type = "git-repo"
    url = "https://github.com/joshskidmore/zsh-fzf-history-search"
    refreshPeriod = "168h"
